/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Sep 26 23:18:02 2016. */

#ifndef PB_GRSIM_COMMANDS_PB_H_INCLUDED
#define PB_GRSIM_COMMANDS_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _grSim_Commands {
    double timestamp;
    bool isteamyellow;
    pb_callback_t robot_commands;
/* @@protoc_insertion_point(struct:grSim_Commands) */
} grSim_Commands;

typedef struct _grSim_Robot_Command {
    uint32_t id;
    float kickspeedx;
    float kickspeedz;
    float veltangent;
    float velnormal;
    float velangular;
    bool spinner;
    bool wheelsspeed;
    bool has_wheel1;
    float wheel1;
    bool has_wheel2;
    float wheel2;
    bool has_wheel3;
    float wheel3;
    bool has_wheel4;
    float wheel4;
/* @@protoc_insertion_point(struct:grSim_Robot_Command) */
} grSim_Robot_Command;

/* Default values for struct fields */

/* Initializer values for message structs */
#define grSim_Robot_Command_init_default         {0, 0, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define grSim_Commands_init_default              {0, 0, {{NULL}, NULL}}
#define grSim_Robot_Command_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define grSim_Commands_init_zero                 {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define grSim_Commands_timestamp_tag             1
#define grSim_Commands_isteamyellow_tag          2
#define grSim_Commands_robot_commands_tag        3
#define grSim_Robot_Command_id_tag               1
#define grSim_Robot_Command_kickspeedx_tag       2
#define grSim_Robot_Command_kickspeedz_tag       3
#define grSim_Robot_Command_veltangent_tag       4
#define grSim_Robot_Command_velnormal_tag        5
#define grSim_Robot_Command_velangular_tag       6
#define grSim_Robot_Command_spinner_tag          7
#define grSim_Robot_Command_wheelsspeed_tag      8
#define grSim_Robot_Command_wheel1_tag           9
#define grSim_Robot_Command_wheel2_tag           10
#define grSim_Robot_Command_wheel3_tag           11
#define grSim_Robot_Command_wheel4_tag           12

/* Struct field encoding specification for nanopb */
extern const pb_field_t grSim_Robot_Command_fields[13];
extern const pb_field_t grSim_Commands_fields[4];

/* Maximum encoded size of messages (where known) */
#define grSim_Robot_Command_size                 55
/* grSim_Commands_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GRSIM_COMMANDS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
