#define RFM12_SPI SPI3

#define RFM12_RCC_SPIPeriph RCC_APB1Periph_SPI3
#define RFM12_RCC_PORTPeriph RCC_AHB1Periph_GPIOC | RCC_AHB1Periph_GPIOD
#define RFM12_NIRQ_RCC_PORTPeriph RCC_AHB1Periph_GPIOE


#define RFM12_PORT GPIOC
#define RFM12_MOSI_PIN GPIO_Pin_12
#define RFM12_MISO_PIN GPIO_Pin_11
#define RFM12_SCK_PIN GPIO_Pin_10

#define RFM12_SS_PORT GPIOD
#define RFM12_SS_PIN GPIO_Pin_0

#define	RFM12_SCK_PIN_AF GPIO_PinSource10
#define	RFM12_MISO_PIN_AF GPIO_PinSource11
#define	RFM12_MOSI_PIN_AF GPIO_PinSource12

#define	RFM12_SPI_AF GPIO_AF_SPI3

#define RFM12_NIRQ_PORT GPIOE
#define RFM12_NIRQ_PIN GPIO_Pin_4

//#define RFM12_FFS_PIN GPIO_Pin_8


