/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.0   2017-10-29

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"

extern "C"{
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "semphr.h"
}

#include "radio/bsp.h"
#include "radio/commands.h"

#include <hal_stm32/interrupt_stm32.h>
//#include "Robo.h"
#include "motor.h"
#include "proto/grSim_Commands.pb.h"
#include "proto/pb_decode.h"
#include "proto/pb_encode.h"

void vTaskNRF24TX( void *pvParameters){
	NRF24L01P *_nrf24=(NRF24L01P*)pvParameters;
	_nrf24->Init();
	_nrf24->Config();
	uint8_t channel;
	uint64_t address;
	channel=92;
	address=0xE7E7E7E700;

	for(;;){
		int delay;
		delay = pdMS_TO_TICKS(100);
		vTaskDelay(delay);

		uint8_t buffer[32];
		uint8_t received_length;
		received_length = usb_device_class_cdc_vcp.GetData(buffer, 32);
		pb_istream_t istream=pb_istream_from_buffer(buffer, received_length);
		grSim_Robot_Command robotcmd;
		uint8_t status=pb_decode(&istream, grSim_Robot_Command_fields, &robotcmd);
		if(status){
			uint8_t robotid=robotcmd.id;
			uint8_t SendBuffer[32];
			pb_ostream_t ostream=pb_ostream_from_buffer(SendBuffer, sizeof(SendBuffer));
			pb_encode(&ostream, grSim_Robot_Command_fields, &robotcmd);//escreve em ostream os dados de robotcmd
			uint8_t size=ostream.bytes_written;
			_nrf24->TxPackage_ESB(channel, address | robotid, 0, (uint8_t*) SendBuffer, size);
			while(_nrf24->Busy()){
				_nrf24->InterruptCallback();
			}
		}
	}
}


void vTaskCmdLine( void *pvParameters){
	for(;;){
		int delay;
		delay = pdMS_TO_TICKS(100);
		vTaskDelay(delay);
		usb_device_class_cdc_vcp.GetData(_usbserialbuffer, 1024);
		cmdline.In(_usbserialbuffer);
		cmdline.Out(_usbserialbuffer);
		if(_usbserialbuffer.Ocupied()){
			usb_device_class_cdc_vcp.SendData(_usbserialbuffer);
		}
	}
}

int main(void)
{
	LIS3DSH_CSN.Set();
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_4);
	//int i = 0;
	usb.Init();
	// robo.Init();

	SysTick_Config(SystemCoreClock/1000);

	xTaskCreate(	vTaskNRF24TX, //ponteiro para a função que implementa a tarefa
		  "Task NRF24TX", 	//nome da função. Para facilitar o debug.
		  700, 		//stack depth
		  (void*)&nrf24, 		//usa task parameter
		  1,			//prioridade 2
		  NULL);
	//xTaskCreate(	vTaskCmdLine, 	//ponteiro para a função que implementa a tarefa
		//  "Task CmdLine", 			//nome da função. Para facilitar o debug.
		  //700, 						//stack depth
		  //NULL, 					//nao usa task parameter
		  //1,						//prioridade 1
		  //NULL);
	vTaskStartScheduler();
	while (1)
	{
		//i++;
	}
}

extern "C" void vApplicationStackOverflowHook( xTaskHandle pxTask, signed char *pcTaskName ){
	( void ) pcTaskName;
	( void ) pxTask;
	for( ;; );
}

extern "C" void vApplicationIdleHook( void ){
	volatile size_t xFreeStackSpace;
	xFreeStackSpace = xPortGetFreeHeapSize();
}

extern "C" void vApplicationTickHook( void ){
}

extern "C" void vApplicationMallocFailedHook( void ){
	for( ;; );
}

